spring.application.name=cestou
spring.datasource.url=jdbc:postgresql://localhost:5433/cestou
spring.datasource.username=postgres
spring.datasource.password=julio2608

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.secretKey=uma-chave-secreta-com-pelo-menos-32-caracteres-aqui-julio